

<form class="custom-form global-search-form" style="display: table;">
    <div class="condensed search-field col-12">
        <input class="search-from icon-close form-control ui-autocomplete-input " type="text" placeholder="Откуда"><span style="display: block;"></span>
            <input type="hidden" name="search-from">
            <span class="geocode"></span>
    </div>
    <div class="condensed small-button col-12 non-mobile-only-change">
            <button type="button" class="reverse-button "><i class="fa fa-arrows-h" aria-hidden="true"></i></button>
    </div>
    <div class="condensed search-field col-12">
        <input class="search-to icon-close form-control ui-autocomplete-input" type="text" placeholder="Куда"><span style="display: block;"></span>
            <input type="hidden" name="search-to">
            <span class="geocode"></span>
    </div>
    <div class="condensed calendar-field col-12">
        <input class="icon-calendar form-calendar ui-autocomplete-input" type="text" placeholder="Когда">
        <span></span>
            <span class="geocode"></span>
    </div>
    <div class="condensed small-button col-12">
        <button type="button" class="search-trip-button"><i class="fa fa-search" aria-hidden="true"></i></button>
    </div>
</form>